[project]
name = "getpcstatsbackend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "psutil>=7.2.2",
    "uvicorn>=0.40.0",
    "zeroconf>=0.143.0",
]
